[package]
name = "communicator"
version = "0.1.0"
authors = ["uu4k <t.shimizu1115@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
